version: '2'

networks:
  epuskesmasnet:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ARGS_MVN_PACKAGE: "-Dmaven.test.skip=true"
    image: "epuskesmas/api:latest"
    networks:
      - epuskesmasnet
    ports:
      - 80:8080
    environment:
      - SERVER_PUBLIC_IP=
      - SERVER_PUBLIC_PORT=
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=
    volumes:
      - /opt/epuskesmas/static:/opt/app/static
    restart: always
